# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  catalog.api:
    build:
      context: "D:\\Personal\\Microservices\\Udemy\\e-shop-microservices"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\AndriiVeremii\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Personal\\Microservices\\Udemy\\e-shop-microservices\\Services\\Catalog\\\
      Catalog.API:/app:rw"
    - "D:\\Personal\\Microservices\\Udemy\\e-shop-microservices:/src:rw"
    working_dir: "/app"
